AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets (DB credentials) and private S3 bucket restricted to the S3 VPC endpoint

Parameters:
  DBUsername:
    Type: String
    Default: dbadmin

Resources:
  DBCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-db-credentials
      Description: "Credentials for RDS Postgres"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username":"${DBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 16
        # Escape backslash properly
        ExcludeCharacters: '"@/\\'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-DBSecret

  DBSecretSSMParam:
    Type: AWS::SSM::Parameter
    DependsOn: DBCredentialsSecret   # ensure secret exists first
    Properties:
      Name: !Sub /${AWS::StackName}/db/secret-arn
      Type: String
      Value: !Ref DBCredentialsSecret   # Ref returns ARN string

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub my-photo-gallery-${AWS::Region}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Images

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowVPCEndpointOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${ImageBucket}
              - !Sub arn:aws:s3:::${ImageBucket}/*
            Condition:
              StringNotEquals:
                aws:SourceVpce: !ImportValue networking-stack-S3VpcEndpointId

Outputs:
  SecretArn:
    Value: !Ref DBCredentialsSecret
    Export:
      Name: !Sub ${AWS::StackName}-SecretArn

  ImageBucketName:
    Value: !Ref ImageBucket
    Export:
      Name: !Sub ${AWS::StackName}-ImageBucketName

  DBSecretSSMParam:
    Value: !Ref DBSecretSSMParam
    Export:
      Name: !Sub ${AWS::StackName}-DBSecretSSMParam
